# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^src/thirt-party/
      - id: check-yaml
      - id: check-added-large-files
        exclude: ^src/thirt-party/
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=120]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--line-length=120, --profile=black]
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-java
  #   rev: 1.3.10
  #   hooks:
  #     - id: validate-html
  #       args: [--remove-mustaches]
