version: "3.9"
services:

  mysql:
    image: mysql:8.0.33
    platform: linux/amd64
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "cr"

  phpmyadmin:
    image: phpmyadmin:5.1.1-apache
    ports:
      - "8888:80"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - PMA_HOST=mysql

volumes:
  mysql-data:
