# Generated by Django 4.2.6 on 2023-10-20 03:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fe_cr", "0002_tickerdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
