# Generated by Django 4.2.6 on 2023-10-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fe_cr", "0004_strategyexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyexecution",
            name="chart_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
